name: CI/CD - Maven Mobile Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        maven-version: '3.8.1'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install Android SDK and ADB
      run: |
        # Atualiza e instala o Android SDK e ADB
        sudo apt-get update
        sudo apt-get install -y android-sdk adb
        export ANDROID_HOME=/usr/lib/android-sdk
        export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;29.0.3" "android-29"

    - name: Install Appium (se estiver usando Appium para testes móveis)
      run: |
        sudo npm install -g appium

    - name: Set up Android Emulator (opcional, se quiser rodar em emulador)
      run: |
        # Criar e inicializar o emulador Android
        echo "no" | avdmanager create avd --name testAVD --package "system-images;android-29;google_apis;x86"
        nohup emulator -avd testAVD -no-window -no-audio -gpu off &
        # Esperar o emulador inicializar
        sleep 60

    - name: Build and run tests with Maven
      run: mvn clean install

    - name: Run Mobile Tests with @regression tag
      run: |
        appium &  # Inicia o Appium server (se estiver usando Appium)
        mvn test -Dtest=* -Dgroups="regression"  # Executa os testes de regressão usando a tag @regression

    - name: Upload Test Results (opcional)
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/test-*.xml
